### ISSUE TITLE
07光照教程代码有些小问题

### ISSUE THREAD

**Issue by Whalesea-Gustav** [MKXJun/DirectX11-With-Windows-SDK-Book#1]
通过ImGui调整SpotLight属性里，原代码直接修改了m_SpotLight的属性
`			ImGui::ColorEdit3("Ambient", &m_SpotLight.ambient.x);
			ImGui::ColorEdit3("Diffuse", &m_SpotLight.diffuse.x);
			ImGui::ColorEdit3("Specular", &m_SpotLight.specular.x);
			ImGui::InputFloat("Spot", &m_SpotLight.spot);
			ImGui::InputFloat("Range", &m_SpotLight.range);
			ImGui::InputFloat3("Attenutation", &m_SpotLight.att.x);
`
按照作者的意思应该是m_PSConstantBuffer.spotLight的属性吧
`			ImGui::ColorEdit3("Ambient", &m_PSConstantBuffer.spotLight.ambient.x);
			ImGui::ColorEdit3("Diffuse", &m_PSConstantBuffer.spotLight.diffuse.x);
			ImGui::ColorEdit3("Specular", &m_PSConstantBuffer.spotLight.specular.x);
			//ImGui::InputFloat("Spot", &m_PSConstantBuffer.spotLight.spot);
			ImGui::SliderFloat("Spot", &m_PSConstantBuffer.spotLight.spot, 0.0f, 10.0f, "%.1f");
			//ImGui::InputFloat("Range", &m_PSConstantBuffer.spotLight.range);
			ImGui::SliderFloat("Range", &m_PSConstantBuffer.spotLight.range, 0.0f, 10.0f, "%.1f");
			ImGui::InputFloat3("Attenutation", &m_PSConstantBuffer.spotLight.att.x);
`

其次，教程的文章里02的标题D3D11Device::CraeteXXXXShader方法--创建着色器，应该是打错字了。

最后，感谢大佬教程，收益匪浅！

**Comment by MKXJun** [comment]
代码的问题已经修正，教程的子标题也已经更改，感谢！
